name = "meme-manager-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# ===========================================
# 全局变量配置
# ===========================================

[vars]
APP_NAME = "Meme Manager"
APP_VERSION = "0.1.0"
LOG_LEVEL = "info"
MAX_FILE_SIZE = "10485760"
ALLOWED_MIME_TYPES = "image/jpeg,image/png,image/gif,image/webp"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60"

# ===========================================
# 开发环境配置 (默认)
# ===========================================

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "meme-manager-db"
database_id = "your_dev_d1_database_id_here"

# R2 存储绑定
[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "meme-manager-assets-dev"

# KV 存储绑定
[[kv_namespaces]]
binding = "CACHE"
id = "your_dev_kv_namespace_id_here"

# ===========================================
# 开发环境配置
# ===========================================

[env.dev]
name = "meme-manager-worker-dev"

[env.dev.vars]
APP_ENV = "dev"
LOG_LEVEL = "debug"
ENABLE_DEV_TOOLS = "true"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "meme-manager-db"
database_id = "your_dev_d1_database_id_here"

[[env.dev.r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "meme-manager-assets-dev"

[[env.dev.kv_namespaces]]
binding = "CACHE"
id = "your_dev_kv_namespace_id_here"

[env.development]
name = "meme-manager-worker-dev"

[env.development.vars]
APP_ENV = "development"
LOG_LEVEL = "debug"
ENABLE_DEV_TOOLS = "true"

[[env.development.d1_databases]]
binding = "DB"
database_name = "meme-manager-db"
database_id = "your_dev_d1_database_id_here"

[[env.development.r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "meme-manager-assets-dev"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "your_dev_kv_namespace_id_here"

# ===========================================
# 预发环境配置
# ===========================================

[env.staging]
name = "meme-manager-worker-staging"

[env.staging.vars]
APP_ENV = "staging"
LOG_LEVEL = "info"
SECURE_HEADERS = "false"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "meme-manager-db"
database_id = "your_staging_d1_database_id_here"

[[env.staging.r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "meme-manager-assets-staging"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "your_staging_kv_namespace_id_here"

# ===========================================
# 生产环境配置
# ===========================================

[env.production]
name = "meme-manager-worker-prod"

[env.production.vars]
APP_ENV = "production"
LOG_LEVEL = "warn"
SECURE_HEADERS = "true"
CORS_STRICT = "true"

[[env.production.d1_databases]]
binding = "DB"
database_name = "meme-manager-db"
database_id = "your_production_d1_database_id_here"

[[env.production.r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "meme-manager-assets-prod"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your_production_kv_namespace_id_here"