name = "meme-manager-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.development]
name = "meme-manager-worker-dev"

[env.staging]
name = "meme-manager-worker-staging"

[env.production]
name = "meme-manager-worker"

# D1 数据库绑定 (占位符)
# [[d1_databases]]
# binding = "DB"
# database_name = "meme-manager-db"
# database_id = "your-database-id"

# R2 存储绑定 (占位符)
# [[r2_buckets]]
# binding = "R2"
# bucket_name = "meme-assets"

# KV 存储绑定 (占位符)
# [[kv_namespaces]]
# binding = "KV"
# id = "your-kv-namespace-id"