name: meme-manager
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pyqt=5.15
  - pip
  - pillow
  - pip:
    - pyqt5-sip
    - fastapi
    - sqlalchemy
    - requests
    - python-magic
    - uvicorn