# Cloudflare Workers 配置
# 这是一个指向实际配置的包装文件

name = "meme-api"
main = "apps/workers/src/index.ts"
compatibility_date = "2024-01-01"

# Workers 配置
workers_dev = true

# 环境变量
[vars]
ENVIRONMENT = "production"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "meme-db"
database_id = ""  # 部署时会自动填入

# R2 存储绑定
[[r2_buckets]]
binding = "R2"
bucket_name = "meme-storage"

# KV 命名空间（可选,用于限流）
# 首次部署时注释掉,创建后再启用
# [[kv_namespaces]]
# binding = "KV"
# id = ""

# 构建配置
[build]
command = "cd packages/shared && npm run build && cd ../../apps/workers && npm install"
cwd = "/"
watch_dirs = ["apps/workers/src", "packages/shared/src"]

# 生产环境配置
[env.production]
name = "meme-api-production"
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "meme-db-production"
database_id = ""

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "meme-storage-production"
